== Contribute

The site welcomes and encourages community contributions. While the project originators will contribute examples as time permits, the main idea behind this project is for the community
to contribute. To that end, we've tried to make contributions as simple as possible.

==== How it works

The site uses AsciiDoc with some infrastructure put in place that allows for additional testing. Every source code example is
verified to be correct, and optionally, if the sample generates output, it is also verified to be correct. Once it passes all checks, the AsciiDoc is
then converted to HTML and published.

All of this is done https://teamcity.jetbrains.com/project.html?projectId=Kotlinbyexample&tab=projectOverview[automatically using TeamCity]. This means that all
contributors need to do is create a simple example. The rest is handled automatically (once the Pull Request is reviewed).

==== How to Contribute

To contribute an example is very straight-forward:

1. Create a new file with the example you want to contribute inside the `docs-src` folder. For example `data-classes.adoc`
2. Write out your example. Make sure you annotated it properly.
3. Optionally add check to verify the output of your example.
4. Submit a pull request.

The site verifies the source code using https://github.com/hhariri/mark-code[`mark-code`]. Check out the https://github.com/hhariri/mark-code/blob/master/README.md[README] for instructions on how to insert
code snippets and what is supported. You can also look at the http://asciidoctor.org/docs/[AsciiDoc reference] for more information about AsciiDoc syntax.

*IMPORTANT*: Make sure you place the file in `docs-src` and not `docs`. `docs` is generated by the build and should not be touched.

==== Avoiding merge conflicts

To avoid merge conflicts with `docs`, which will happen if you push to master, if you're using IntelliJ IDEA, add the folder to the list of Ignored Files. Make sure not to modify the `.gitignore` otherwise it won't allow the build server to check in these files either (which is in fact needed).

==== Getting Help

If you get stuck, contact one of the https://twitter.com/hhariri[authors] or reach out to us on http://slack.kotlinlang.org[Kotlin Slack], on the *#kotlin-by-example* channel.

