=== Extension functions

Extension functions allow us to attach custom functions to any library or custom code we write. You can extend String, Collection or 
any other known type with some custom behavior. Given example creates `isContainedBy` extension function that we can directly call on 
any kind of `T` type, as though it was part of the standard library.

[source,kotlin]
----
private fun <T> T.isContainedBy(collection: Collection<T>) = collection.contains(this)//<1>

fun main(args: Array<String>) {
    println("a in [a,b,c] : ${"a".isContainedBy(listOf("a", "b", "c"))}")//<2>
    println("a in [d,e,f] : ${"a".isContainedBy(listOf("d", "e", "f"))}")//<2>
}
----
<1> Read more about signature of https://kotlinlang.org/docs/reference/extensions.html[extension functions]. Signature
is very much like standard function signature, with addition that we need to specify type (`T` in this case) we're attaching function to.
<2> We call our extension function on `"a"` String variable.

Having extension functions support we have unlimited power of extending functionality of any known types if we think they're missing some APIs.