name: Verify samples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run a verifier
        uses: AlexanderPrendota/kotlin-samples-verifier@master
        with:
          push-repository: 'https://github.com/AlexanderPrendota/kotlin-compiler-server'
          tag-filter: '#tag="code" & class="language-run-kotlin" & !validate="false"'
          push-path: 'src/test/resources/test-compile-data/jvm/kotlin-by-example'
          username: '${{ secrets.KOTLIN_BY_EXAMPLE_TOKEN }}' #token with an access to create PR in push-repository and issue in this repository

